#!/bin/sh

rcup -K config/zsh/{.zlogin,.zlogout,.zshrc,.zshenv,.zprofile}

if [ ! -d ~/.config/nvim/pack/minpac/opt/minpac ]; then
  git clone https://github.com/k-takata/minpac.git \
    ~/.config/nvim/pack/minpac/opt/minpac
fi

if [ ! -d ~/.zplug ]; then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  ~/.zplug/bin
fi

